In [3]:
import pandas as pd
import matplotlib as plt
import numpy as np
import requests
from bs4 import BeautifulSoup as BS
import re
import time

In [4]:
url = 'https://nuforc.org/wp-admin/admin-ajax.php?action=get_wdtable&table_id=1&wdt_var1=Post&wdt_var2=-1'
params = {
    'action': 'get_wdtable',
    'table_id': '1',
    'wdt_var1': 'Post',
    'wdt_var2': '-1',
}

data = {
    'draw': '1',
    'start': '0',
    'length': '80000',
    'search[value]': '',
    'search[regex]': 'false',
    'wdtNonce': '2ad4551c87',  # This looks like a security nonce, ensure it's correctly handled
}

data.update({
    'order[0][column]': '1',
    'order[0][dir]': 'desc',
})

r = requests.post(url, params=params, data=data)

r

In [5]:
url = 'https://nuforc.org/wp-admin/admin-ajax.php?action=get_wdtable&table_id=1&wdt_var1=Post&wdt_var2=-1'
params = {
    'action': 'get_wdtable',
    'table_id': '1',
    'wdt_var1': 'Post',
    'wdt_var2': '-1',
}

data = {
    'draw': '1',
    'start': '0',
    'length': '80000',
    'search[value]': '',
    'search[regex]': 'false',
    'wdtNonce': '9cc2436813',  # This looks like a security nonce, ensure it's correctly handled
}

data.update({
    'order[0][column]': '1',
    'order[0][dir]': 'desc',
})

r = requests.post(url, params=params, data=data)

r

In [6]:
ufo = r.json()

In [7]:
ufo_df2 = pd.DataFrame(ufo['data'])
ufo_df2.head()

,0,1,2,3,4,5,6,7,8,9
0,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 14:20,Shepherdsville,KY,USA,Orb,Several sightings over several years.,02/15/2024,02/15/2024,None
1,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 06:21,Greenville,SC,USA,Circle,"Object moving slowing across the sky, suddenly...",02/15/2024,02/15/2024,None
2,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 02:30,Mount Gambier,South Australia,Australia,Formation,"All were low, groups of two stars moving about...",02/14/2024,02/15/2024,None
3,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:45,None,VA,USA,Light,Standing to the west of this object it hung in...,02/15/2024,02/15/2024,None
4,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:44,Somers,CT,USA,Unknown,"Odd, flashing object I could only describe dur...",02/14/2024,02/15/2024,Y

In [8]:
ufo_df1 = pd.DataFrame(ufo['data'])
ufo_df1.head()

,0,1,2,3,4,5,6,7,8,9
0,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 14:20,Shepherdsville,KY,USA,Orb,Several sightings over several years.,02/15/2024,02/15/2024,None
1,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 06:21,Greenville,SC,USA,Circle,"Object moving slowing across the sky, suddenly...",02/15/2024,02/15/2024,None
2,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 02:30,Mount Gambier,South Australia,Australia,Formation,"All were low, groups of two stars moving about...",02/14/2024,02/15/2024,None
3,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:45,None,VA,USA,Light,Standing to the west of this object it hung in...,02/15/2024,02/15/2024,None
4,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:44,Somers,CT,USA,Unknown,"Odd, flashing object I could only describe dur...",02/14/2024,02/15/2024,Y

In [9]:
ufo_df3 = pd.concat([ufo_df1,ufo_df2])
ufo_df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 160000 entries, 0 to 79999
Data columns (total 10 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       160000 non-null  object
 1   1       160000 non-null  object
 2   2       159288 non-null  object
 3   3       154900 non-null  object
 4   4       160000 non-null  object
 5   5       152826 non-null  object
 6   6       159924 non-null  object
 7   7       160000 non-null  object
 8   8       160000 non-null  object
 9   9       8360 non-null    object
dtypes: object(10)
memory usage: 13.4+ MB

In [10]:
ufo_df3

,0,1,2,3,4,5,6,7,8,9
0,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 14:20,Shepherdsville,KY,USA,Orb,Several sightings over several years.,02/15/2024,02/15/2024,None
1,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 06:21,Greenville,SC,USA,Circle,"Object moving slowing across the sky, suddenly...",02/15/2024,02/15/2024,None
2,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 02:30,Mount Gambier,South Australia,Australia,Formation,"All were low, groups of two stars moving about...",02/14/2024,02/15/2024,None
3,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:45,None,VA,USA,Light,Standing to the west of this object it hung in...,02/15/2024,02/15/2024,None
4,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:44,Somers,CT,USA,Unknown,"Odd, flashing object I could only describe dur...",02/14/2024,02/15/2024,Y
...,...,...,...,...,...,...,...,...,...,...
79995,<a data-content='Open' href='/sighting/?id=805...,11/23/2010 18:00,North Bergen,NJ,USA,Other,THE OBJECT CHANGED COLOURS OVER NYC& N.J. IN H...,03/22/2011,03/23/2011,None
79996,<a data-content='Open' href='/sighting/?id=108...,11/23/2010 16:55,Albany (3 hrs W of; on I-90 near Exit 44),NY,USA,Other,Gun metal black crescent with 6 window-glowing...,03/28/2014,04/04/2014,None
79997,<a data-content='Open' href='/sighting/?id=791...,11/23/2010 06:30,Monument Valley,UT,USA,Changing,looked like a worm in the sky oozing off itsel...,12/02/2010,01/05/2011,None
79998,<a data-content='Open' href='/sighting/?id=790...,11/23/2010 06:00,Washougal,WA,USA,Oval,Bright big oval shaped light in the sky.,11/27/2010,01/05/2011,None
79999,<a data-content='Open' href='/sighting/?id=790...,11/23/2010 05:49,North Babylon,NY,USA,Other,"I could see 5 lights around the bottom, closes...",11/23/2010,01/05/2011,None

In [11]:
ufo_df3.columns = [
    'image_link',
    'occurred',
    'city',
    'state',
    'country',
    'shape',
    'summary',
    'reported',
    'posted',
    'image']

ufo_df3

,image_link,occurred,city,state,country,shape,summary,reported,posted,image
0,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 14:20,Shepherdsville,KY,USA,Orb,Several sightings over several years.,02/15/2024,02/15/2024,None
1,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 06:21,Greenville,SC,USA,Circle,"Object moving slowing across the sky, suddenly...",02/15/2024,02/15/2024,None
2,<a data-content='Open' href='/sighting/?id=180...,02/15/2024 02:30,Mount Gambier,South Australia,Australia,Formation,"All were low, groups of two stars moving about...",02/14/2024,02/15/2024,None
3,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:45,None,VA,USA,Light,Standing to the west of this object it hung in...,02/15/2024,02/15/2024,None
4,<a data-content='Open' href='/sighting/?id=180...,02/14/2024 22:44,Somers,CT,USA,Unknown,"Odd, flashing object I could only describe dur...",02/14/2024,02/15/2024,Y
...,...,...,...,...,...,...,...,...,...,...
79995,<a data-content='Open' href='/sighting/?id=805...,11/23/2010 18:00,North Bergen,NJ,USA,Other,THE OBJECT CHANGED COLOURS OVER NYC& N.J. IN H...,03/22/2011,03/23/2011,None
79996,<a data-content='Open' href='/sighting/?id=108...,11/23/2010 16:55,Albany (3 hrs W of; on I-90 near Exit 44),NY,USA,Other,Gun metal black crescent with 6 window-glowing...,03/28/2014,04/04/2014,None
79997,<a data-content='Open' href='/sighting/?id=791...,11/23/2010 06:30,Monument Valley,UT,USA,Changing,looked like a worm in the sky oozing off itsel...,12/02/2010,01/05/2011,None
79998,<a data-content='Open' href='/sighting/?id=790...,11/23/2010 06:00,Washougal,WA,USA,Oval,Bright big oval shaped light in the sky.,11/27/2010,01/05/2011,None
79999,<a data-content='Open' href='/sighting/?id=790...,11/23/2010 05:49,North Babylon,NY,USA,Other,"I could see 5 lights around the bottom, closes...",11/23/2010,01/05/2011,None

In [12]:
ufo_df3.to_csv('nuforc.csv')